# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='convidado',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='acompanhante',
            field=models.IntegerField(default=0),
        ),
    ]
