# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171112_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='RSVP',
        ),
    ]
