# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171112_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='oauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.TextField(default='c966c6fc09974becaa208180e8f5aa44')),
                ('client_secret', models.TextField(default='93375efa5f3f4055a9740bfc6367121d')),
                ('grant_type', models.TextField(default='authorization_code')),
                ('redirect_uri', models.TextField(default='adrianochia.pythonanywhere.com/tag')),
                ('code', models.TextField(default='14421ece8c3642aca864a3a01f37980f')),
            ],
        ),
    ]
