# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_oauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='oauth',
        ),
    ]
