# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foto',
            new_name='grupo_foto',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
        migrations.RenameField(
            model_name='grupo_foto',
            old_name='foto',
            new_name='grupo_foto',
        ),
    ]
